import type { NextPage } from 'next'
import Head from 'next/head'
import { ToDo } from '@/components/pages/ToDo'

const ToDoPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next Simple Template | ToDo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToDo />
    </>
  )
}

export default ToDoPage
