import Head from 'next/head'

import { Documents } from './components/Documents'
import { Title } from './components/Title'
import styles from './Top.module.scss'

export const Top = () => {
  return (
    <>
      <Head>
        <title>Next Simple Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <Title />
          <Documents />
        </div>
      </main>
    </>
  )
}
